### ISSUE TITLE
How can I replicate this on my machine

### ISSUE THREAD

**Issue by ketgg** [sarveshrulz/nixos_config#1]
Hi, I am new to Nixos and looking for some configs, can you please tell the steps to follow so that I could get your setup on my machine. Thanks.

**Comment by sarveshrulz** [comment]
Hello, you just need to change hostname (carbon) in flake.nix and then change hardware-configuration.nix in system/carbon to the one generated for your machine, also be sure to go through configuration.nix in the same directory, regarding secrets, it's just a normal set of values, it's obviously a private repo as it contains values that cannot be shared publicly like keys, etc.
Also you might need to change few configurations in user.nix (which are common dotfiles which gets linked to ~/.config) and change username and stuff. Just go through it...
